### PR TITLE
Visual C++ static analysis warnings

### PR DESCRIPTION
**Pull request by thradams**
These changes aim to remove and show some problems pointed by the visual studio code analysis.

### CODE REVIEW

**Comment by nemequ** [comment]
0d8de3c6c45b57a6ce79cf317378639820aac6b6 is a (squashed) version of this, which resolves the issues instead of adding comments.

The remaining one is the warning in mtx_trylock—according to https://msdn.microsoft.com/en-us/library/hh324208.aspx it can be fixed by annotating the function (mtx_lock and mtx_unlock should probably also be annotated), but I have no idea how to do go about that and I don't have VS so I can't really test, but I'd be happy to merge a PR which properly resolves that.

**Comment by thradams** [comment]
I am new to github. I am having problems to sincronize the main branch to my branch. How to do that?
My pull request was very confusing because of it.

**Comment by nemequ** [comment]
Something like:

```
git remote add upstream https://github.com/tinycthread/tinycthread.git
git remote update
git reset --hard upstream/master
```

**Comment by thradams** [comment]
Thanks.
There are more warnings on VS++ 2015 RC.
The return of timespec_get is not being checked,

For some reason the annotations to ignore the mtx_trylock warning is not working. I will try more later.

Visual C++ 2015 

".. <time.h> now defines the C11 timespec type and the timespec_get function. In addition, the TIME_UTC macro, for use with the timespec_get function, is now defined."

http://blogs.msdn.com/b/vcblog/archive/2014/06/18/crt-features-fixes-and-breaking-changes-in-visual-studio-14-ctp1.aspx

**Pull request closed without merging**
